# Generated by Django 3.2.8 on 2021-10-26 21:09

from django.db import migrations, models
import django.db.models.deletion
import elida.apps.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_str', models.CharField(max_length=16)),
                ('slug', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('html', models.CharField(max_length=64)),
                ('charge', models.SmallIntegerField()),
                ('natoms', models.PositiveSmallIntegerField()),
            ],
            bases=(elida.apps.mixins.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Isotopologue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_formula_str', models.CharField(max_length=32)),
                ('iso_slug', models.CharField(max_length=32)),
                ('inchi_key', models.CharField(max_length=32)),
                ('dataset_name', models.CharField(max_length=16)),
                ('version', models.PositiveIntegerField()),
                ('html', models.CharField(max_length=64)),
                ('mass', models.FloatField()),
                ('ground_el_state_str', models.CharField(default='', max_length=64)),
                ('vib_state_dim', models.SmallIntegerField(default=0)),
                ('molecule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='molecule.molecule')),
            ],
            bases=(elida.apps.mixins.ModelMixin, models.Model),
        ),
    ]
