# Generated by Django 3.2.8 on 2021-10-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('molecule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='molecule',
            old_name='natoms',
            new_name='number_atoms',
        ),
    ]
