# Generated by Django 3.2.8 on 2021-10-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molecule', '0002_rename_natoms_molecule_number_atoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='isotopologue',
            name='number_states',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='isotopologue',
            name='number_transitions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='isotopologue',
            name='vib_state_dim',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
