# Generated by Django 3.2.8 on 2021-10-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('molecule', '0002_isotopologue_resolving_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isotopologue',
            old_name='resolving_html',
            new_name='resolving_vib_html',
        ),
    ]
