# Generated by Django 3.2.8 on 2021-10-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molecule', '0003_auto_20211028_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isotopologue',
            name='number_states',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='isotopologue',
            name='number_transitions',
            field=models.PositiveIntegerField(),
        ),
    ]
