# Generated by Django 3.2.8 on 2021-10-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('molecule', '0004_isotopologue_resolving_el_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isotopologue',
            name='resolving_el_html',
        ),
        migrations.RemoveField(
            model_name='isotopologue',
            name='resolving_vib_html',
        ),
    ]
