# Generated by Django 3.2.8 on 2021-10-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0002_transition_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transition',
            old_name='d_energy',
            new_name='delta_energy',
        ),
    ]
