# Generated by Django 3.2.8 on 2021-10-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0004_alter_transition_delta_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='delta_energy',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
