# Generated by Django 3.2.8 on 2021-10-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0005_alter_transition_delta_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='final_state_state_html',
            field=models.CharField(default='<sup>final</sup>state<sub>html</sub>', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transition',
            name='initial_state_state_html',
            field=models.CharField(default='<sup>initial</sup>state</sub>html</sub>', max_length=128),
            preserve_default=False,
        ),
    ]
