# Generated by Django 3.2.9 on 2021-11-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0006_auto_20211029_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='final_state_state_html_notags',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transition',
            name='final_state_state_sort_key',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transition',
            name='initial_state_state_html_notags',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transition',
            name='initial_state_state_sort_key',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
