# Generated by Django 3.2.9 on 2021-11-07 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0007_auto_20211107_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transition',
            name='final_state_state_html_notags',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='final_state_state_sort_key',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='html',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='initial_state_state_html_notags',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='initial_state_state_sort_key',
        ),
    ]
