# Generated by Django 3.2.9 on 2021-11-07 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0008_auto_20211107_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transition',
            name='final_state_state_html',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='initial_state_state_html',
        ),
    ]
