# Generated by Django 3.2.8 on 2021-10-15 13:57

from django.db import migrations, models
import django.db.models.deletion
import elida.apps.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('molecule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_str', models.CharField(max_length=64)),
                ('lifetime', models.FloatField(null=True)),
                ('energy', models.FloatField()),
                ('state_html', models.CharField(max_length=128)),
                ('isotopologue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='molecule.isotopologue')),
            ],
            bases=(elida.apps.mixins.ModelMixin, models.Model),
        ),
    ]
