# Generated by Django 3.2.8 on 2021-10-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='html',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
