# Generated by Django 3.2.8 on 2021-10-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0003_auto_20211028_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='number_transitions_from',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='state',
            name='number_transitions_to',
            field=models.PositiveIntegerField(),
        ),
    ]
