# Generated by Django 3.2.8 on 2021-10-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0004_auto_20211028_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='state_html',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
