# Generated by Django 3.2.9 on 2021-11-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0005_state_state_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='el_state_html_notags',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='state_html_notags',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='vib_state_html_notags',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
