# Generated by Django 3.2.9 on 2021-11-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0006_auto_20211106_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='state_sort_key',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='vib_state_sort_key',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
