# Generated by Django 3.2.9 on 2021-11-07 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0007_auto_20211106_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='html',
        ),
    ]
