# Generated by Django 3.2.12 on 2022-02-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transition',
            name='branching_ratio',
        ),
    ]
