# Generated by Django 3.2.12 on 2022-02-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0002_auto_20220202_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
