# Generated by Django 3.2.23 on 2024-07-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0002_remove_transition_branching_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='vib_state_html',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='state',
            name='vib_state_html_notags',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='state',
            name='vib_state_sort_key',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='state',
            name='vib_state_str',
            field=models.CharField(max_length=128),
        ),
    ]
