# Generated by Django 3.2.12 on 2022-02-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0003_alter_molecule_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isotopologue',
            name='inchi_key',
        ),
    ]
