# Generated by Django 3.2.7 on 2021-10-05 14:06

from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('formula_str', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('html', models.CharField(max_length=64)),
                ('charge', models.SmallIntegerField()),
                ('natoms', models.SmallIntegerField()),
            ],
            bases=(utils.models.ProvenanceMixin, utils.models.ReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Isotopologue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iso_formula_str', models.CharField(max_length=32)),
                ('iso_slug', models.CharField(max_length=32)),
                ('inchi_key', models.CharField(max_length=32)),
                ('dataset_name', models.CharField(max_length=16)),
                ('version', models.PositiveIntegerField()),
                ('html', models.CharField(max_length=64)),
                ('mass', models.FloatField()),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifetimes.formula')),
            ],
            bases=(utils.models.ProvenanceMixin, utils.models.ReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_str', models.CharField(max_length=64)),
                ('energy', models.FloatField()),
                ('state_html', models.CharField(max_length=64)),
                ('isotopologue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifetimes.isotopologue')),
            ],
            bases=(utils.models.ProvenanceMixin, utils.models.ReprMixin, models.Model),
        ),
    ]
