# Generated by Django 3.2.7 on 2021-10-06 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifetimes', '0002_auto_20211006_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='final_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_to_set', to='lifetimes.state'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='initial_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_from_set', to='lifetimes.state'),
        ),
    ]
