# Generated by Django 3.2.8 on 2021-10-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifetimes', '0002_alter_state_state_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='slug',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
