# Generated by Django 3.2.8 on 2021-10-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifetimes', '0003_auto_20211006_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='lifetime',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transition',
            name='branching_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transition',
            name='partial_lifetime',
            field=models.FloatField(),
        ),
    ]
